### PR TITLE
Kibana container breakout

### PR DESCRIPTION
**Pull request by Duckmanjbr**
Kibana has been broken out into a few different roles:
Kibana-role (Kibana is now both containerized and bare metal)
Lighttpd-role (Lighttpd is a reverse proxy used to authenticate w/out x-pack)
Elk-role (Elk role is designed to install all elk config add-ons like dashboards and logstash injects)

### CODE REVIEW

**Comment by grantcurell** [comment]
If Kibana is running those two things with custom configurations then they should be part of the Kibana role and we'll have two instances of nginx running, but in different and completely separate containers. Same thing with xkcdpass. I'll git dcode's thoughts.

**Comment by dcode** [comment]
Agree with @grantcurell. We also want to swap out nginx entirely for lighttpd. See #200. Currently using lighttpd for docket and want to

**Comment by Duckmanjbr** [comment]
To make sure I understand before going down this road.  Did I just hear a
software engineer tell me not to break something out?  You want me to put
xkcdpass & lighttpd(nginx) into the same container as Kibana?  This makes
my job so easy!  Are you sure that's what you want?  I can't speak to
"custom configurations".  @dcode can you confirm that we need to keep them
separate?

**Comment by dcode** [comment]
No. Kibana should be its own container. I was thinking config would all be the same role... But it probably is the smart thing to do to split to a new role/new container. xkcdpass is only used to configure basic auth, so it can probably go into the webserver container/role

**Pull request merged**
